version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: demo_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - demomysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123

volumes:
  demomysql:
    external: true
